---
- hosts: centos
  tasks:
    - name: epel_repo
      yum: name=epel-release
    - name: ensure nginx is at the latest version
      yum: name=httpd state=present
    - name: start httpd
      service:
          name: httpd
          state: restarted
    - name: example copying file with owner and permissions
      copy:
       src: /etc/ansible/index.html 
       dest: /var/www/html/index.html
       mode: 0644
